#!/bin/bash
set -e
#FQBD=atmel-avr-xminis:avr:atmega328pb_xplained_mini
#FQBD=arduino:avr:nano
#FQBD=stm32duino:STM32F1:genericSTM32F103C:upload_method=STLinkMethod
FQBD=STM32:stm32:GenF1
arduino-cli compile -v -b $FQBD
arduino-cli upload -v -b $FQBD
